spring:
  application:
    name: Film Catalog Application
  datasource:
    url: jdbc:postgresql://localhost:5433/film_catalog_db
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



